### ISSUE TITLE
[More Information on source code]

### ISSUE THREAD

**Issue by vinayak618** [learnedsystems/SOSD#1]
Hi Team,

Thank you so much for the benchmark paper and implementation of various index structures.
Is there any more documentation about the source code. It is little difficult to understand the models represented in rust, generating the C++ code for indexes.

Also few days back i saw the paper "Learning to Search" mentioned in ML for systems conference'19 accepted papers. Is this paper same of that?

Thanks,
Vinayak N B

**Comment by andreaskipf** [comment]
Hi Vinayak,

There’s a separate repository that contains the RMI implementation &
documentation:
https://learned.systems/RMI
(Not sure if you saw that.)

That being said, we plan to add more documentation.

And yes, it is the same paper.

Thanks for your feedback!

Andreas
