### ISSUE TITLE
Possibly wrong cache-miss measurement

### ISSUE THREAD

**Issue by alihadian** [learnedsystems/SOSD#12]
When I use the SOSD benchmark, the cache-misses are high and don't seem real:

index, time sec, cycles, instructions, **L1-misses, LLC-misses**, branch-misses, task-clock,   scale,  IPC, CPUs,  GHz 
RESULT: Oracle,     0.00,   6.05,        11.02,      **0.25,       0.33**,          0.00,       1.52, 1000000, 1.82, 1.01, 3.99 
RESULT:   rmi,     0.31, 831.12,       228.74,     **15.36,      38.71**,          3.83,     214.89, 1000000, 0.28, 0.70, 3.87 
RESULT: RadixSpline,     0.31, 1238.91,       281.28,     **21.08,      51.05**,          3.12,     313.53, 1000000, 0.23, 1.00, 3.95 
RESULT: BinarySearch,     0.65, 2570.39,       398.27,     **87.29,     185.30**,         13.59,     645.73, 1000000, 0.15, 1.00, 3.98 

In RMI, for example, L1-miss = 15.36, LLC-misses=38.71. First of all, how is it possible that the L1 miss rate is less than LLC miss rate (I suppose all LLC misses were caused by an L1-miss, no?

More importantly, the numbers don't make sense. For Binary search over 200M records, we have at most log(200M,2)=27 memory accesses. Considering that some of the accesses will be cached, I expect both L1 and LLC misses to be 20-something, NOT what the benchmark reports for binary search (L1-misses=87.29, LLC-misses=185.30) !!

Besides, when I manually run the indexes (or the whole benchmark) in Intel VTune and see the miss-rates on each section, the miss rates are entirely different and are close to what I expect (For binary search: LLC miss rate = 20.3).

Why are the measurements so different? I am just very confused.

I use [the original commit of SOSD for theMLforSys paper](https://github.com/learnedsystems/SOSD/tree/mlforsys19) but I suppose all version use the same probing mechanism.

**Comment by andreaskipf** [comment]
Hi Ali,

First of all, sorry for the slow response. The perf counters are normalized by `lookups.size()`. Can you please check that you are actually performing that many iterations of the lookup code and that `repeats` is set to `1`?

We measured around 40 LLC misses for binary search (per iteration of the [lookup loop](https://github.com/learnedsystems/SOSD/blob/mlforsys19/benchmark.h#L106)). Cf. Figure 3c: https://learned.systems/papers/sosd.pdf

Andreas

**Comment by andreaskipf** [comment]
Closing this for now. @alihadian please let me know whether I should re-open it.
