### ISSUE TITLE
Compile errors (prepare.sh)

### ISSUE THREAD

**Issue by niceIrene** [learnedsystems/SOSD#17]
Hi, I am running prepare.sh, but I got the following errors. It looks like there are some missing files.

[ 75%] Building CXX object CMakeFiles/benchmark.dir/benchmarks/benchmark_rbs.cc.o
[ 75%] Building CXX object CMakeFiles/benchmark.dir/benchmarks/benchmark_pgm.cc.o
[ 75%] Building CXX object CMakeFiles/benchmark.dir/benchmarks/benchmark_rmi.cc.o
[ 75%] Building CXX object CMakeFiles/benchmark.dir/benchmarks/benchmark_rs.cc.o
In file included from /Users/.../SOSD-master/benchmarks/benchmark_rmi.cc:3:
/Users/.../SOSD-master/dtl/../competitors/rmi_search.h:4:10: fatal error: 'rmi/all_rmis.h' file not found
#include "rmi/all_rmis.h"
         ^~~~~~~~~~~~~~~~
In file included from /Users/.../SOSD-master/benchmarks/benchmark_pgm.cc:4:
In file included from /Users/.../SOSD-master/dtl/../competitors/pgm_index.h:11:
In file included from /Users/.../SOSD-master/competitors/PGM-index/include/pgm_index.hpp:24:
/Users/.../SOSD-master/competitors/PGM-index/include/piecewise_linear_model.hpp:20:6: fatal error: Compile with -fopenmp
    #error Compile with -fopenmp
     ^
4 warnings and 1 error generated.
4 warnings and 1 error generated.
make[2]: *** [CMakeFiles/benchmark.dir/benchmarks/benchmark_rmi.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/benchmark.dir/benchmarks/benchmark_pgm.cc.o] Error 1
make[1]: *** [CMakeFiles/benchmark.dir/all] Error 2
make: *** [all] Error 2

**Comment by andreaskipf** [comment]
Hi Irene, I believe you need to run build_rmis.sh first. See reproduce.sh in the root directory.

**Comment by niceIrene** [comment]
Thanks a lot! I just ran the "scripts/download_rmis.sh" before, so the error occurs. Your answer helps. I still have the following error. I am wondering how I could disable some baselines and added new datasets (any files I need to modify?). Really appreciate your help!

**In file included from /Users/yinlin/Downloads/SOSD-master/benchmarks/benchmark_pgm.cc:4:
In file included from /Users/yinlin/Downloads/SOSD-master/dtl/../competitors/pgm_index.h:11:
In file included from /Users/yinlin/Downloads/SOSD-master/competitors/PGM-index/include/pgm_index.hpp:24:
/Users/yinlin/Downloads/SOSD-master/competitors/PGM-index/include/piecewise_linear_model.hpp:20:6: fatal error: Compile with -fopenmp
    #error Compile with -fopenmp**

**Comment by niceIrene** [comment]
Thanks a lot! I just ran the "scripts/download_rmis.sh" before, so the error occurs. Your answer helps. I still have the following error. I am wondering how I could disable some baselines and added new datasets (any files I need to modify?). Really appreciate your help!

In file included from /Users/.../SOSD-master/benchmarks/benchmark_pgm.cc:4:
In file included from /Users/.../SOSD-master/dtl/../competitors/pgm_index.h:11:
In file included from /Users/.../SOSD-master/competitors/PGM-index/include/pgm_index.hpp:24:
/Users/.../SOSD-master/competitors/PGM-index/include/piecewise_linear_model.hpp:20:6: fatal error: Compile with -fopenmp
#error Compile with -fopenmp

**Comment by RyanMarcus** [comment]
Hi,

You'll need to have OpenMP installed to compile the PGM index. I'm not sure this works on a Mac -- maybe @andreaskipf or @alexandervanrenen could speak to that.

At the moment, we don't have support tor disabling baselines at compile time. At runtime, you can use a command-line flag to only run certain competitors, for example, `--only RMI`.

You can specify your own data and lookup key file when running the compiled benchmark, that should allow you to use your own data. :)

Thanks,

Ryan

**Comment by andreaskipf** [comment]
To compile it on Mac, you need to comment out the openmp stuff. PGM will
still work, it just won't build in parallel.

**Comment by niceIrene** [comment]
Thank you so much! It works.

**Comment by andreaskipf** [comment]
Great. You're welcome!
