### ISSUE TITLE
Output files (containing only RMI and RS)

### ISSUE THREAD

**Issue by niceIrene** [learnedsystems/SOSD#18]
Hi, I have generated the result files for the experiments. (execute.sh) My output only has results for the RMI and RS index methods. I am wondering if it is correct or I did something wrong in the other steps. Should we see the results for all index methods? Thanks!

**Comment by andreaskipf** [comment]
Hi Irene, can you please try commenting out the PGM lines in `benchmark.cc`?

**Comment by niceIrene** [comment]
It works! Thank you. I have a follow-up question regarding using other datasets. Can we use the ones whose keys are not uint64 or uint32? I am trying to use the [longitudes dataset](https://drive.google.com/file/d/1zc90sD6Pze8UM_XYDmNjzPLqmKly8jKl/view) whose keys are binary. It looks like we need to change some settings. Thanks!

**Comment by andreaskipf** [comment]
Great!

We don't support doubles right now, unfortunately. You would need to
convert them to integers.

**Comment by niceIrene** [comment]
Thanks!
