### ISSUE TITLE
[RadixSpline] memory leak and a suggested fix

### ISSUE THREAD

**Issue by jmftrindade** [learnedsystems/SOSD#5]
Caught it in our test suite, which runs sanitizer checks including Google's [`LeakSanitizer`](https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer).

Suggested fix -> add a destructor that ensures the `radix_hint_` heap allocated vector gets freed correctly:

```cpp
  ~RadixSpline() {
    if (radix_hint_ != nullptr) {
      delete[](radix_hint_);
    }
  }
```

**Comment by RyanMarcus** [comment]
Nice catch, there's probably a ton of these throughout SOSD. One of the reasons we are missing them is because some of the competitors require special AVX instructions that break `valgrind`. Maybe someone should give this sanitizer a shot?

**Comment by RyanMarcus** [comment]
Ah, I think the current version stores `radix_hint_` as a `std::vector` member, so that should get cleaned up automatically when the class is dropped. Can you give that a shot? 

Hopefully Andreas & Alex will have a better RadixSpline implementation soon.

**Comment by jmftrindade** [comment]
Cool: yes, if `radix_hint_` is no longer a `uint32_t*` array, that memleak should not be there anymore.

I see there's been a number of recent changes on the code structure. We'll wait for the "standalone" version before we change our setup to use `git submodule` for it instead of a local copy.

**Comment by RyanMarcus** [comment]
That's a good idea -- I'll tag @andreaskipf and @alexandervanrenen here so they can close this and notify us when it's ready.

**Comment by RyanMarcus** [comment]
A standalone version of RS is available here: https://learned.systems/rs
