### ISSUE TITLE
The commit corresponding to the original SOSD paper not tagged or citable

### ISSUE THREAD

**Issue by alihadian** [learnedsystems/SOSD#7]
The commit used in the SOSD SysML paper is for 12 Dec 2019:
https://github.com/learnedsystems/SOSD/commit/87d34efbabbd9cd0a1c30502886f12c81cbd9727

Please **tag this commit** so that we can refer to it in the papers that are already concluded and are under review. 

Also, what is the next stable, cite-able release after the SOSD SysML paper?

**Comment by RyanMarcus** [comment]
Hi Ali,

That commit [is now tagged](https://github.com/learnedsystems/SOSD/tree/sysml_2019). Thanks for pointing that out.

The SOSD SysML paper is the most recent paper published, although we hope to have a draft published of our new results in the next few days (hopefully the next arxiv cycle). The results in that draft will be based on the `vldb_2020` tag.

I'll update this issue when it becomes available.

**Comment by alihadian** [comment]
Thanks @RyanMarcus :)

**Comment by alihadian** [comment]
Ah, sorry. The SOSD paper was not published in SysML 2019, it was in NuroIPS 2019. Could you please change the ```sysml_2019``` tag to something like ```neuroips_2019``` or whatever you prefer?

Actually SysML is in February each year and NuroIPS is in December, which means not only the tag is incorrect, but also it makes the citation look one year older / outdated.

**Comment by RyanMarcus** [comment]
I'll fix the tag shortly, sorry about that. 

Here's the draft: https://arxiv.org/abs/2006.12804

**Comment by alihadian** [comment]
Thanks for sharing the draft, Ryan!
I'm looking forward to the renaming of the tag :)

**Comment by RyanMarcus** [comment]
The tag is now `mlforsys19`.
